apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus.monitoring.svc.cluster.local:9090']

      - job_name: 'demo-app'
        static_configs:
          - targets: ['demo-app.monitoring.svc.cluster.local:9113']
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 5s\n\nscrape_configs:\n  - job_name: 'prometheus'\n    static_configs:\n      - targets: ['prometheus.monitoring.svc.cluster.local:9090']\n\n  - job_name: 'demo-app'\n    static_configs:\n      - targets: ['demo-app.monitoring.svc.cluster.local:9113']\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-config","namespace":"monitoring"}}
  creationTimestamp: "2025-11-28T23:07:35Z"
  name: prometheus-config
  namespace: monitoring
  resourceVersion: "372372"
  uid: 7cfe520f-25cc-4ca7-bcdd-c4dcbbe1ec48
